-- PALLET_CHAOS: generated by tools/content-editor (do not hand-edit;
-- re-Save from the content editor, or maintain editor_project.lua).
return function(mod)

  mod.content.pokemon:patch("MAGIKARP", {
    baseExp = 20,
    baseStats = {
      attack = 10,
      defense = 55,
      hp = 20,
      special = 20,
      speed = 80,
    },
    catchRate = 255,
    dex = 129,
    dexEntry = {
      heightFt = 2,
      heightIn = 11,
      kind = "FISH",
      text = "_MagikarpDexEntry",
      weight = 220,
    },
    evolutions = {
      {
              level = 20,
              method = "LEVEL",
              species = "GYARADOS",
            },
    },
    frontSize = 6,
    growthRate = "SLOW",
    id = "MAGIKARP",
    index = 133,
    learnset = {
      {
              level = 15,
              move = "TACKLE",
            },
    },
    level1Moves = {
      "SPLASH",
    },
    name = "MAGIKARP",
    tmhm = {},
    types = {
      "WATER",
    },
  })

  mod.content.maps:register("PALLET_EAST", {
    blocks = {
      62,
      40,
      44,
      44,
      44,
      44,
      44,
      41,
      63,
      59,
      29,
      30,
      15,
      15,
      15,
      62,
      59,
      15,
      15,
      15,
      40,
      36,
      87,
      87,
      87,
      87,
      87,
      37,
      43,
      112,
      101,
      100,
      15,
      53,
      15,
      36,
      112,
      15,
      15,
      15,
      36,
      87,
      87,
      87,
      87,
      87,
      87,
      87,
      37,
      110,
      11,
      11,
      11,
      10,
      10,
      10,
      10,
      15,
      15,
      15,
      80,
      82,
      80,
      7,
      7,
      7,
      7,
      7,
      7,
      66,
      111,
      111,
      111,
      111,
      111,
      111,
      10,
      15,
      15,
      15,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      85,
      15,
      15,
      15,
      98,
      80,
      11,
      11,
      11,
      11,
      11,
      11,
      79,
      99,
      82,
      82,
      82,
      82,
      82,
      82,
      82,
      15,
      15,
      15,
      78,
      70,
      19,
      19,
      19,
      19,
      19,
      19,
      71,
      77,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      78,
      74,
      26,
      26,
      26,
      26,
      26,
      26,
      75,
      77,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      80,
      82,
      82,
      82,
      82,
      82,
      82,
      82,
      82,
      79,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
      15,
    },
    borderBlock = 0,
    connections = {
      west = {
        map = "PALLET_TOWN",
        offset = 0,
      },
    },
    height = 9,
    id = "PALLET_EAST",
    index = 1001,
    label = "Pallet East",
    objects = {},
    signs = {},
    tileset = "OVERWORLD",
    warps = {},
    width = 20,
  })

  mod.content.encounters:register("PALLET_EAST", {
    grass = {
      rate = 20,
      slots = {
        {
                  level = 1,
                  species = "BULBASAUR",
                },
        {
                  level = 1,
                  species = "PIKACHU",
                },
        {
                  level = 1,
                  species = "ODDISH",
                },
        {
                  level = 1,
                  species = "BELLSPROUT",
                },
        {
                  level = 1,
                  species = "MAGNEMITE",
                },
        {
                  level = 1,
                  species = "CHARMANDER",
                },
        {
                  level = 1,
                  species = "SQUIRTLE",
                },
        {
                  level = 1,
                  species = "ABRA",
                },
      },
    },
  })

  mod.content.maps:patch("PALLET_TOWN", {
    blocks = {
      82,
      79,
      82,
      82,
      79,
      11,
      80,
      82,
      82,
      80,
      78,
      1,
      56,
      57,
      1,
      1,
      56,
      57,
      1,
      77,
      78,
      8,
      60,
      61,
      1,
      8,
      60,
      61,
      1,
      77,
      78,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      77,
      49,
      1,
      119,
      86,
      1,
      12,
      13,
      14,
      1,
      10,
      78,
      1,
      116,
      116,
      1,
      16,
      58,
      0,
      1,
      77,
      78,
      1,
      1,
      1,
      1,
      119,
      86,
      119,
      49,
      77,
      78,
      10,
      29,
      30,
      49,
      116,
      116,
      10,
      49,
      77,
      80,
      10,
      101,
      100,
      97,
      97,
      97,
      97,
      97,
      79,
    },
    borderBlock = 11,
    connections = {
      east = {
        map = "PALLET_EAST",
        offset = 0,
      },
      north = {
        map = "ROUTE_1",
        offset = -0,
      },
      south = {
        map = "ROUTE_21",
        offset = -0,
      },
      west = {
        map = "PALLET_WEST",
        offset = -4,
      },
    },
    height = 9,
    id = "PALLET_TOWN",
    index = 0,
    label = "PalletTown",
    objects = {
      {
              hidden = true,
              index = 1,
              movement = "STAY",
              name = "PALLETTOWN_OAK",
              range = "NONE",
              sprite = "SPRITE_OAK",
              text = "TEXT_PALLETTOWN_OAK",
              x = 8,
              y = 5,
            },
      {
              index = 2,
              movement = "WALK",
              name = "PALLETTOWN_GIRL",
              range = "ANY_DIR",
              sprite = "SPRITE_GIRL",
              text = "TEXT_PALLETTOWN_GIRL",
              x = 3,
              y = 8,
            },
      {
              index = 3,
              movement = "WALK",
              name = "PALLETTOWN_FISHER",
              range = "ANY_DIR",
              sprite = "SPRITE_FISHER",
              text = "TEXT_PALLETTOWN_FISHER",
              x = 11,
              y = 14,
            },
    },
    signs = {
      {
              text = "TEXT_PALLETTOWN_OAKSLAB_SIGN",
              x = 13,
              y = 13,
            },
      {
              text = "TEXT_PALLETTOWN_SIGN",
              x = 7,
              y = 9,
            },
      {
              text = "TEXT_PALLETTOWN_PLAYERSHOUSE_SIGN",
              x = 3,
              y = 5,
            },
      {
              text = "TEXT_PALLETTOWN_RIVALSHOUSE_SIGN",
              x = 11,
              y = 5,
            },
    },
    tileset = "OVERWORLD",
    warps = {
      {
              destMap = "REDS_HOUSE_1F",
              destWarp = 1,
              x = 5,
              y = 5,
            },
      {
              destMap = "BLUES_HOUSE",
              destWarp = 1,
              x = 13,
              y = 5,
            },
      {
              destMap = "OAKS_LAB",
              destWarp = 2,
              x = 12,
              y = 11,
            },
    },
    width = 10,
  })

  mod.content.maps:register("PALLET_WEST", {
    blocks = {
      62,
      63,
      63,
      63,
      63,
      63,
      63,
      63,
      63,
      59,
      40,
      62,
      63,
      63,
      63,
      63,
      63,
      63,
      59,
      41,
      40,
      40,
      15,
      1,
      51,
      108,
      54,
      44,
      41,
      41,
      40,
      40,
      52,
      111,
      111,
      52,
      53,
      44,
      41,
      41,
      40,
      40,
      44,
      44,
      43,
      87,
      87,
      87,
      112,
      41,
      40,
      36,
      87,
      87,
      37,
      43,
      87,
      6,
      87,
      37,
      40,
      44,
      2,
      3,
      44,
      41,
      53,
      76,
      52,
      116,
      40,
      44,
      44,
      44,
      44,
      41,
      26,
      92,
      26,
      26,
      36,
      6,
      42,
      44,
      44,
      41,
      11,
      1,
      1,
      1,
      28,
      28,
      36,
      87,
      87,
      37,
      28,
      28,
      28,
      28,
    },
    borderBlock = 0,
    connections = {
      east = {
        map = "PALLET_TOWN",
        offset = 4,
      },
    },
    environment = "outside",
    height = 10,
    id = "PALLET_WEST",
    index = 1005,
    label = "Pallet west",
    objects = {
      {
              index = 1,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_TRAINER1",
              trainerClass = "OPP_SUSPICIOUS_BIRB",
              trainerParty = 1,
              x = 15,
              y = 12,
            },
      {
              index = 2,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ2",
              x = 19,
              y = 13,
            },
      {
              index = 3,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ3",
              x = 17,
              y = 16,
            },
      {
              index = 4,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ5",
              x = 8,
              y = 12,
            },
      {
              index = 5,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ6",
              x = 13,
              y = 3,
            },
      {
              index = 6,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ7",
              x = 6,
              y = 8,
            },
      {
              index = 7,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ8",
              x = 3,
              y = 18,
            },
      {
              index = 8,
              movement = "STAY",
              range = "DOWN",
              sprite = "SPRITE_BOULDER",
              text = "TEXT_PALLET_WEST_OBJ8",
              x = 12,
              y = 18,
            },
    },
    outdoor = true,
    signs = {},
    tileset = "OVERWORLD",
    warps = {},
    width = 10,
  })

  mod.content.encounters:register("PALLET_WEST", {
    grass = {
      rate = 25,
      slots = {
        {
                  level = 3,
                  species = "PIDGEY",
                },
      },
    },
  })

  mod.content.maps:patch("REDS_HOUSE_1F", {
    blocks = { 4, 9, 8, 7, 15, 15, 15, 15, 15, 1, 2, 15, 15, 11, 15, 15 },
    borderBlock = 10,
    connections = {},
    height = 4,
    id = "REDS_HOUSE_1F",
    index = 37,
    label = "RedsHouse1F",
    objects = {
      {
              index = 1,
              movement = "STAY",
              name = "REDSHOUSE1F_MOM",
              range = "LEFT",
              sprite = "SPRITE_MOM",
              text = "TEXT_REDSHOUSE1F_MOM",
              x = 5,
              y = 4,
            },
    },
    signs = {
      {
              text = "TEXT_REDSHOUSE1F_TV",
              x = 3,
              y = 1,
            },
    },
    tileset = "REDS_HOUSE_1",
    warps = {
      {
              destMap = "LAST_MAP",
              destWarp = 1,
              x = 2,
              y = 7,
            },
      {
              destMap = "LAST_MAP",
              destWarp = 1,
              x = 3,
              y = 7,
            },
      {
              destMap = "REDS_HOUSE_2F",
              destWarp = 1,
              x = 7,
              y = 1,
            },
      {
              destMap = "REDS_HOUSE_3F",
              destWarp = 1,
              x = 5,
              y = 1,
            },
    },
    width = 4,
  })

  mod.content.maps:register("REDS_HOUSE_3F", {
    blocks = { 16, 17, 7, 15, 15, 15, 12, 15, 15 },
    borderBlock = 0,
    connections = {},
    height = 3,
    id = "REDS_HOUSE_3F",
    index = 1002,
    label = "RedsHouse3F",
    objects = {
      {
              index = 1,
              movement = "STAY",
              name = "MR.MIME",
              range = "RIGHT",
              sprite = "SPRITE_MONSTER",
              text = "TEXT_REDS_HOUSE_3F_OBJ1",
              x = 0,
              y = 3,
            },
    },
    signs = {},
    tileset = "REDS_HOUSE_2",
    warps = {
      {
              destMap = "REDS_HOUSE_1F",
              destWarp = 4,
              x = 5,
              y = 1,
            },
    },
    width = 3,
  })

  mod.content.field:patch("superRod", {
    PALLET_TOWN = {
      {
              level = 15,
              species = "TENTACOOL",
            },
      {
              level = 15,
              species = "POLIWAG",
            },
    },
  })

  mod.content.text:override("_PALLET_WESTTrainer1After", ".......")
  mod.content.text:override("_PALLET_WESTTrainer1Battle", ".......")
  mod.content.text:override("_PALLET_WESTTrainer1Won", "......")
  mod.content.text:override("_PALLET_WESTWild8", "Gyaoo!")
  mod.content.text:override("_PALLET_WESTWild9", "Gyaoo!")
  mod.content.text:override("_RedsHouse1FMomWakeUpText", "MOM: Right.\
All boys leave\11home some day.\11It said so on TV.\12PROF.OAK, next\
door, is looking\11for you. \
 \
 \
 and honey, please stay out of my room.")

  mod.content.text_pointers:patch("Pallet west", {
    TEXT_PALLET_WEST_OBJ8 = {
      text = "_PALLET_WESTWild8",
    },
  })

  mod.content.text_pointers:patch("RedsHouse1F", {
    TEXT_REDSHOUSE1F_MOM = {
      asm = true,
      label = "RedsHouse1FMomText",
      text = "_RedsHouse1FMomWakeUpText",
    },
  })

  mod.content.text_pointers:patch("RedsHouse3F", {
    TEXT_REDS_HOUSE_3F_OBJ1 = {
      text = "_REDS_HOUSE_3F_OBJ1",
    },
  })

  mod.content.trainers:register("OPP_SUSPICIOUS_BIRB", {
    aiMods = { 1 },
    baseMoney = 20,
    basePic = "SPRITE_PAPER",
    id = "OPP_SUSPICIOUS_BIRB",
    index = 200,
    name = "SUSPICIOUS BIRB",
    parties = {
      {
              {
                        level = 5,
                        species = "PIDGEY",
                      },
            },
      {
              {
                        level = 12,
                        species = "DITTO",
                      },
            },
    },
    pic = mod.path .. "/assets/suspicious_bird.png",
  })

  mod.content.trainers:register("OPP_SUSPICIOUS_BIRD", {
    aiMods = { 1 },
    baseMoney = 20,
    basePic = "OPP_BLACKBELT",
    id = "OPP_SUSPICIOUS_BIRD",
    index = 200,
    name = "SUSPICIOUS BIRD",
    parties = {
      {
              {
                        level = 5,
                        species = "PIDGEY",
                      },
            },
    },
  })



  do
    local _ceTrainerHeaders = {
      ["Pallet west"] = {
        {
                  after = "_PALLET_WESTTrainer1After",
                  battle = "_PALLET_WESTTrainer1Battle",
                  event = "MOD_PALLET_CHAOS_BEAT_PALLET_WEST_1",
                  opponent = "OPP_SUSPICIOUS_BIRB",
                  party = 1,
                  range = 0,
                  won = "_PALLET_WESTTrainer1Won",
                },
      },
    }
    if mod.content.trainer_headers then
      for label, bucket in pairs(_ceTrainerHeaders) do
        local patch = { [0] = mod.DELETE }
        for idx, hdr in pairs(bucket) do patch[idx] = hdr end
        mod.content.trainer_headers:patch(label, patch)
      end
    else
      mod.events:on("mods.loaded", function(ev)
        local th = ev.data and ev.data.trainer_headers
        if type(th) ~= "table" then return end
        for label, bucket in pairs(_ceTrainerHeaders) do
          local dest = th[label]
          if type(dest) ~= "table" then
            dest = {}
            th[label] = dest
          end
          for idx, hdr in pairs(bucket) do
            if type(idx) == "number" and type(hdr) == "table" then
              dest[idx] = hdr
            end
          end
        end
      end)
    end
  end

  mod.content.map_scripts:register("REDS_HOUSE_3F", {
    talk = {
      TEXT_REDS_HOUSE_3F_NPC1 = {
        {
                  "label",
                  "end",
                },
      },
      TEXT_REDS_HOUSE_3F_OBJ1 = {
        {
                  "show_text",
                  "Mr.MIME is shivering badly......  You reach out to comfort him....... he recoils with fear......  Maybe you should stay out of your mom's room. ",
                },
        {
                  "label",
                  "end",
                },
      },
    },
  })

  -- event flags declared in the content editor:
  --   MOD_PALLET_CHAOS_BEAT_PALLET_WEST_1

  mod.content.map_songs:override("PALLET_EAST", "Music_PalletTown")

  mod.content.map_songs:override("PALLET_WEST", "Music_PalletTown")

  mod.content.field:patch("intro", {
    studio = {},
  })

  mod.content.field:patch("badgeGates", { ["PALLET_WEST"] = mod.DELETE })

  mod.content.field:patch("darkMaps", {
    maps = {
      "ROCK_TUNNEL_1F",
      "ROCK_TUNNEL_B1F",
    },
    palOffset = 6,
  })

end
